//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our translators have extensive linguistic knowledge and translate solely and exclusively towards their source language.
        ///Our working mode is based on different tools and processes. Every project you entrust us follows the same process, in accordance with a rigorous methodology that guarantees an optimal result..
        /// </summary>
        public static string HowDoWeWork_Description {
            get {
                return ResourceManager.GetString("HowDoWeWork_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we work?.
        /// </summary>
        public static string HowDoWeWork_Header {
            get {
                return ResourceManager.GetString("HowDoWeWork_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices vary according to the length, difficulty and format of each text, projects and documents. Our services start from $0,03 dollars per source word. However, there is not just one price, so please contact us to verify it based on your own order. We usually make special price for number of pages or big projects and even for quick and easy translations..
        /// </summary>
        public static string HowMuchDoesItCost_Description {
            get {
                return ResourceManager.GetString("HowMuchDoesItCost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much does a translation cost?.
        /// </summary>
        public static string HowMuchDoesItCost_Header {
            get {
                return ResourceManager.GetString("HowMuchDoesItCost_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our desire and goal is the continuous improvement and to provide our customers with high-quality services, therefore all opinions are important to us and help us to move forward.
        ///                    Because we value the opinion of our customers, we look forward to hearing your comments!.
        /// </summary>
        public static string Questions_Description {
            get {
                return ResourceManager.GetString("Questions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions_Header {
            get {
                return ResourceManager.GetString("Questions_Header", resourceCulture);
            }
        }
    }
}
