//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.ContactUs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.ContactUs.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motustranslations@gmail.com.
        /// </summary>
        public static string ContactDetails_Email {
            get {
                return ResourceManager.GetString("ContactDetails_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 (253) 243-2338 / +54 9 3564 336421.
        /// </summary>
        public static string ContactDetails_Phone {
            get {
                return ResourceManager.GetString("ContactDetails_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7.
        /// </summary>
        public static string ContactDetails_WorkingHours {
            get {
                return ResourceManager.GetString("ContactDetails_WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs_Title {
            get {
                return ResourceManager.GetString("ContactUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        public static string Form_Email {
            get {
                return ResourceManager.GetString("Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string Form_Email_Error_Required {
            get {
                return ResourceManager.GetString("Form_Email_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us a Message.
        /// </summary>
        public static string Form_Header {
            get {
                return ResourceManager.GetString("Form_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Form_Message {
            get {
                return ResourceManager.GetString("Form_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your message..
        /// </summary>
        public static string Form_Message_Error_Required {
            get {
                return ResourceManager.GetString("Form_Message_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        public static string Form_Name {
            get {
                return ResourceManager.GetString("Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        public static string Form_Name_Error_Required {
            get {
                return ResourceManager.GetString("Form_Name_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string Form_Phone {
            get {
                return ResourceManager.GetString("Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        public static string Form_Phone_Error_Required {
            get {
                return ResourceManager.GetString("Form_Phone_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to submit your message. Please verify your inputs and try again..
        /// </summary>
        public static string Form_Submit_Error {
            get {
                return ResourceManager.GetString("Form_Submit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received your message. One of our representatives will contact you within 48hs..
        /// </summary>
        public static string Form_Submit_Success {
            get {
                return ResourceManager.GetString("Form_Submit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;description&quot; lang=&quot;en&quot; content=&quot;Motus Translations is a company that provides translations services from English to Spanish and Spanish to English. We are headquartered in Córdoba, Argentina but we also operate in United States and other countries around the world. You can contact us through the Contact section in our website, by sending an email to motustranslations@gmail.com, or by calling us to +1 (253) 243-2338 or +54 9 3564 336421.&quot;&gt;.
        /// </summary>
        public static string Tag_Meta_Description {
            get {
                return ResourceManager.GetString("Tag_Meta_Description", resourceCulture);
            }
        }
    }
}
