//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.WhoAreWe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.WhoAreWe.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natalia Domínguez is an enthusiastic professional translator. She exclusively renders from English into Spanish —her mother tongue— and provides translation services for Business, Finance, IT, Social and Medical Science sectors. Most part of her projects come from the following fields: Finance (financial documents); Journalism (different pieces of news and articles); general texts concerning Medical topics (health insurance documents, medical guides, etc); Technology issues such as manuals and guidelines fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NataliaDominguez_Description {
            get {
                return ResourceManager.GetString("NataliaDominguez_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/in/domingueznatalia16/en.
        /// </summary>
        public static string NataliaDominguez_LinkedinUri {
            get {
                return ResourceManager.GetString("NataliaDominguez_LinkedinUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natalia Domínguez.
        /// </summary>
        public static string NataliaDominguez_Name {
            get {
                return ResourceManager.GetString("NataliaDominguez_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Translator.
        /// </summary>
        public static string NataliaDominguez_Title {
            get {
                return ResourceManager.GetString("NataliaDominguez_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string OurTeam_Header {
            get {
                return ResourceManager.GetString("OurTeam_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romina Castagno is a professional-grade human translator who provides document translation services from English into Spanish.
        ///She works with several specialization areas and a wide range of industries: Energy (oil, gas and alternative energy), Business, Software, Environment, Literature, Fashion, Games applications, among others. 
        ///She has done edition and proofreading (style, grammar, spelling) of translations for companies in India, USA, Europe, and Argentina. 
        ///Her tasks consist in working with platfor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RominaCastagno_Description {
            get {
                return ResourceManager.GetString("RominaCastagno_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ar.linkedin.com/in/romina-castagno-55834348/en.
        /// </summary>
        public static string RominaCastagno_LinkedinUri {
            get {
                return ResourceManager.GetString("RominaCastagno_LinkedinUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romina Castagno.
        /// </summary>
        public static string RominaCastagno_Name {
            get {
                return ResourceManager.GetString("RominaCastagno_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Translator.
        /// </summary>
        public static string RominaCastagno_Title {
            get {
                return ResourceManager.GetString("RominaCastagno_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanina Fassi is a professional English-Spanish translator specializing in Medicine, Health Care, Pharmaceutical, and Psychology.
        ///Investigating and discovering about different subjects drives her to continually improve her knowledge of the translation industry. She has translated and edited for many different companies within several fields, such as sports, journalism, fashion, to name a few.
        ///Building long-term client relationship is essential for her, thus she commits herself to satisfy the clients’ requi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VaninaFassi_Description {
            get {
                return ResourceManager.GetString("VaninaFassi_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ar.linkedin.com/in/vaninafassi/en.
        /// </summary>
        public static string VaninaFassi_LinkedinUri {
            get {
                return ResourceManager.GetString("VaninaFassi_LinkedinUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanina Fassi.
        /// </summary>
        public static string VaninaFassi_Name {
            get {
                return ResourceManager.GetString("VaninaFassi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Translator.
        /// </summary>
        public static string VaninaFassi_Title {
            get {
                return ResourceManager.GetString("VaninaFassi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As self-motivated professionals, we have set up our own enterprise Re- Make translations where effective communication is our main purpose; and our commitment is to focus on delivering efficient language services. We believe, as detail- oriented linguists, that quality is paramount in the world of translation, and finishing translation assignments on time is an essential part of it.
        ///&lt;br&gt;
        ///&lt;strong&gt;Re-Make Translations&lt;/strong&gt; was founded on a simple business premise to complete professional translation ser [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhoAreWe_Description {
            get {
                return ResourceManager.GetString("WhoAreWe_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Are We?.
        /// </summary>
        public static string WhoAreWe_Header {
            get {
                return ResourceManager.GetString("WhoAreWe_Header", resourceCulture);
            }
        }
    }
}
