//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.WhoAreWe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.WhoAreWe.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OurTeam_Header {
            get {
                return ResourceManager.GetString("OurTeam_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romina Castagno is a professional translator who provides document translation services from English into Spanish.
        ///She works with several specialization areas and a wide range of industries: Energy (oil, gas and alternative energy), Business, Software, Environment, Literature, Fashion, Games applications, among others. 
        ///She has done edition and proofreading (style, grammar, spelling) of translations for companies in India, USA, Europe, and Argentina. 
        ///Her tasks consist in working with platforms and tools [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RominaCastagno_Description {
            get {
                return ResourceManager.GetString("RominaCastagno_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ar.linkedin.com/in/romina-castagno-55834348/en.
        /// </summary>
        public static string RominaCastagno_LinkedinUri {
            get {
                return ResourceManager.GetString("RominaCastagno_LinkedinUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romina Castagno.
        /// </summary>
        public static string RominaCastagno_Name {
            get {
                return ResourceManager.GetString("RominaCastagno_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Translator.
        /// </summary>
        public static string RominaCastagno_Title {
            get {
                return ResourceManager.GetString("RominaCastagno_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Motus&lt;/strong&gt; is a new translation company placing emphasis on dedicated Project Management and excellent customer service. We offer the widest range of document translation services with accuracy, industry-specific experience and a comprehensive network of knowledgeable translators.
        ///In Motus Translations, clients receive personal attention and service. The company ensures each project, big or small, is given equal attention. 
        ///We offer multiple levels of service based on client needs, ranging fro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhoAreWe_Description {
            get {
                return ResourceManager.GetString("WhoAreWe_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Are We?.
        /// </summary>
        public static string WhoAreWe_Header {
            get {
                return ResourceManager.GetString("WhoAreWe_Header", resourceCulture);
            }
        }
    }
}
