//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.HowDoWeWork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.HowDoWeWork.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                    &lt;li&gt;We commit ourselves to safeguard the interests of our clients as our own and divulge no confidential information.&lt;/li&gt;
        ///                    &lt;li&gt;Our translation team and collaborators shall not disclose information acquired during the course of their assignments.&lt;/li&gt;
        ///                    &lt;li&gt;Translated documents remain the client&apos;s property.&lt;/li&gt;
        ///                    &lt;li&gt;Our translation team and our company may only disclose information with the permission of our clients (or if [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Confidentiality_Description {
            get {
                return ResourceManager.GetString("Confidentiality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality.
        /// </summary>
        public static string Confidentiality_Header {
            get {
                return ResourceManager.GetString("Confidentiality_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our compromise is to deliver translated assignments with the high standard of quality and always considering our clients’ urgency. To accomplish this, we work with qualified and specialised linguists. In addition, if any translated document does not fulfill our client’s expectation, &lt;strong&gt;CHECK THIS &lt;/strong&gt;we will provide a revision and a version free of charge to satisfy our clients’ needs (conditions and terms are stipulated from the start.).
        /// </summary>
        public static string Guarantees_Description {
            get {
                return ResourceManager.GetString("Guarantees_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantees.
        /// </summary>
        public static string Guarantees_Header {
            get {
                return ResourceManager.GetString("Guarantees_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;&lt;strong&gt;Working mode&lt;/strong&gt;&lt;/h3&gt;
        ///Our translators have extensive linguistic knowledge and translate solely and exclusively towards their source language.
        ///Our working mode is based on different tools and processes. Every project you entrust us follows the same process, in accordance with a rigorous methodology that guarantees an optimal result. According to the project, the steps are as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;&lt;strong&gt;Analysis of the Project&lt;/strong&gt;:
        ///The project manager analyses the files, (format, spec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowDoWeWork_Description {
            get {
                return ResourceManager.GetString("HowDoWeWork_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we work?.
        /// </summary>
        public static string HowDoWeWork_Header {
            get {
                return ResourceManager.GetString("HowDoWeWork_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We translate from English into Spanish different types of documents related to the following subject matter:
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;Industry (Energy, Oil, Cosmetic, Tourism, Pharmaceutical, Construction.)&lt;/li&gt;
        ///                    &lt;li&gt;Business (Commerce, Finance, Economics, Accountancy, Legal.)&lt;/li&gt;
        ///                    &lt;li&gt;Technology (Information Technology, Video Games applications, Computing.)&lt;/li&gt;
        ///                    &lt;li&gt;Culture (Fashion, Travel, Cookery, Music, Literature.)&lt;/li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Services_Description {
            get {
                return ResourceManager.GetString("Services_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services_Header {
            get {
                return ResourceManager.GetString("Services_Header", resourceCulture);
            }
        }
    }
}
