//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.HowDoWeWork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.HowDoWeWork.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;ul&gt;
        ///                    &lt;li&gt;We do not divulge confidential information.&lt;/li&gt;
        ///                    &lt;li&gt;Our translation team and collaborators cannot disclose information acquired during the course of their assignments.&lt;/li&gt;
        ///                    &lt;li&gt;Our translation team and our company may only disclose information with the permission of our clients (or if the law requires disclosure).&lt;/li&gt;
        ///                &lt;/ul&gt;
        ///                Our confidentiality principles are based on the following Codes of Ethics:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Confidentiality_Description {
            get {
                return ResourceManager.GetString("Confidentiality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality.
        /// </summary>
        public static string Confidentiality_Header {
            get {
                return ResourceManager.GetString("Confidentiality_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We work with qualified and specialized linguists. We ensure our translated documents are taken by professionals who specialize on your required field. We deliver translated assignments with high standard of quality and we always consider our clients’ urgency. In addition, if there are problems, mistakes or even doubts you will like to clarify with our professionals, please write an email to us with your inquiry and we will respond as soon as the translator and editor reply back to it..
        /// </summary>
        public static string Guarantees_Description {
            get {
                return ResourceManager.GetString("Guarantees_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantees.
        /// </summary>
        public static string Guarantees_Header {
            get {
                return ResourceManager.GetString("Guarantees_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Motus, we offer high-quality translation services that focus on the needs of your business. As part of our translation services we assign a dedicated team to pay special attention to your project. In essence, you can rest assured that your project is well attended to, leaving you free to devote more of your time to your business. Every project you entrust us follows the same process, in accordance with a rigorous methodology of Translators, Editors and Proof readers..
        /// </summary>
        public static string HowDoWeWork_Description {
            get {
                return ResourceManager.GetString("HowDoWeWork_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we work?.
        /// </summary>
        public static string HowDoWeWork_Title {
            get {
                return ResourceManager.GetString("HowDoWeWork_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///We have experience that runs from:
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;Medical document translations&lt;/li&gt;
        ///                    &lt;li&gt;Letter translations&lt;/li&gt;
        ///                    &lt;li&gt;Commercial documents translations&lt;/li&gt;
        ///                    &lt;li&gt;Marketing materials translations&lt;/li&gt;
        ///                    &lt;li&gt;Legal documents translations&lt;/li&gt;
        ///                    &lt;li&gt;Fashion and cosmetics translations&lt;/li&gt;
        ///                    &lt;li&gt;IT documents translations&lt;/li&gt;
        ///                    &lt;li&gt;Technica [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Services_Description {
            get {
                return ResourceManager.GetString("Services_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services_Header {
            get {
                return ResourceManager.GetString("Services_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;description&quot; lang=&quot;en&quot; content=&quot;Motus Translations is a company that provides translations services from English to Spanish and Spanish to English. All our jobs go through a standardized process that includes translation, edition, and proof-reading following ATA (American Translators Association) and AATI (American Translators Association) standards.&quot;&gt;.
        /// </summary>
        public static string Tag_Meta_Description {
            get {
                return ResourceManager.GetString("Tag_Meta_Description", resourceCulture);
            }
        }
    }
}
