//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationsSite.Resources.GetQuote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationsSite.Resources.GetQuote.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date:.
        /// </summary>
        public static string Form_Deadline {
            get {
                return ResourceManager.GetString("Form_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details:.
        /// </summary>
        public static string Form_Details {
            get {
                return ResourceManager.GetString("Form_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your message..
        /// </summary>
        public static string Form_Details_Error_Required {
            get {
                return ResourceManager.GetString("Form_Details_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        public static string Form_Email {
            get {
                return ResourceManager.GetString("Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string Form_Email_Error_Required {
            get {
                return ResourceManager.GetString("Form_Email_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string Form_File {
            get {
                return ResourceManager.GetString("Form_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit this form to receive a FREE translation quote.
        /// </summary>
        public static string Form_Header {
            get {
                return ResourceManager.GetString("Form_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages:.
        /// </summary>
        public static string Form_Languages {
            get {
                return ResourceManager.GetString("Form_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;option value=&quot;english-spanish&quot;&gt;English to Spanish&lt;/option&gt;
        ///&lt;option value=&quot;spanish-english&quot;&gt;Spanish to English&lt;/option&gt;
        ///&lt;option value=&quot;other&quot;&gt;Other (Specify on &quot;More Details&quot; section)&lt;/option&gt;.
        /// </summary>
        public static string Form_Languages_Select {
            get {
                return ResourceManager.GetString("Form_Languages_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        public static string Form_Name {
            get {
                return ResourceManager.GetString("Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        public static string Form_Name_Error_Required {
            get {
                return ResourceManager.GetString("Form_Name_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string Form_Phone {
            get {
                return ResourceManager.GetString("Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        public static string Form_Phone_Error_Required {
            get {
                return ResourceManager.GetString("Form_Phone_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type:.
        /// </summary>
        public static string Form_ProjectType {
            get {
                return ResourceManager.GetString("Form_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;option value=&quot;all&quot;&gt;Complete Translation Project&lt;/option&gt;
        ///&lt;option value=&quot;translation&quot;&gt;Translation&lt;/option&gt;
        ///&lt;option value=&quot;edition&quot;&gt;Edition&lt;/option&gt;
        ///&lt;option value=&quot;proofreading&quot;&gt;Proof Reading&lt;/option&gt;
        ///&lt;option value=&quot;other&quot;&gt;Other&lt;/option&gt;.
        /// </summary>
        public static string Form_ProjectType_Select {
            get {
                return ResourceManager.GetString("Form_ProjectType_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a FREE Quote.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to submit your message. Please verify your inputs and try again..
        /// </summary>
        public static string Form_Submit_Error {
            get {
                return ResourceManager.GetString("Form_Submit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received your message. One of our representatives will contact you within 48hs..
        /// </summary>
        public static string Form_Submit_Success {
            get {
                return ResourceManager.GetString("Form_Submit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word count:.
        /// </summary>
        public static string Form_WordCount {
            get {
                return ResourceManager.GetString("Form_WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already know the word count of your document or you have the document nearby you can obtain a free quote by sending the form from this page.
        ///&lt;br&gt;
        ///Please, remember to specify your contact details, source and target language, delivery date and type of service..
        /// </summary>
        public static string GetQuote_Description {
            get {
                return ResourceManager.GetString("GetQuote_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I get a free quote?.
        /// </summary>
        public static string GetQuote_Header {
            get {
                return ResourceManager.GetString("GetQuote_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Quote.
        /// </summary>
        public static string GetQuote_Title {
            get {
                return ResourceManager.GetString("GetQuote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;description&quot; lang=&quot;en&quot; content=&quot;Motus Translations is a company that provides translations services from English to Spanish and Spanish to English. Get a FREE quote now by simply answering few questions. You can get a free translation quote either by sending us the document to translate, or by specifying the project features and the count of words to translate.&quot;&gt;.
        /// </summary>
        public static string Tag_Meta_Description {
            get {
                return ResourceManager.GetString("Tag_Meta_Description", resourceCulture);
            }
        }
    }
}
